kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: belenot/spring-app
        volumeMounts:
          name: log
          mountPath: /deployment/log
      - name: fluent-bit
        image: fluent/flient-bit
        volumeMounts:
        - name: log
          mountPath: /deployment/log
        - name: fluent-bit-config
          mountPath: ???
      volumes:
      - name: log
        emptyDir: {}
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
---
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    name: http-8080
    port: 8080
    targetPort: 8080
    protocol: TCP
  
        

