apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-virtualservice
spec:
  hosts:
  - httpbin
#  - httpbin.default.svc.cluster.local # short name resolved
  gateways:
  - istio-system/nginx2-egressgateway
  - mesh
  http:
  - name: "httpbin"
    match:
    - name: "mesh"
      gateways:
      - mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
    rewrite:
      authority: httpbin.default.svc.cluster.local
  - name: "httpbin"
    match:
    - name: "nginx2-egressgateway"
      gateways:
      - istio-system/nginx2-egressgateway
      port: 80
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 80
        
    
