apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: simple-web-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-resources
      version: v1
  template:
    metadata:
      labels:
        app: simple-web-resources
        version: v1
    spec:
      containers:
      - name: simple-web-resources
        image: belenot/simple-web-resources
        ports:
        - containerPort: 8080
          name: http-8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-resources
spec:
  selector:
    app: simple-web-resources
    version: v1
  ports:
  - name: http-80
    port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-web-resources
spec:
  hosts:
  - '*'
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - name: "simple-web-resources"
    match:
    - uri:
        prefix: "/simple-web-resources/"
    - uri:
        prefix: "/simple-web-resources"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: simple-web-resources.default.svc.cluster.local
        port:
          number: 80
        
